Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 03/05/2022
Var
// Seção de Declarações das variáveis 
   c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   c <- 100
   para c <- 100 ate 0 passo -10 faca
      escreval(c)
   fimpara


Fimalgoritmo