Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 21/04/2022
Var
// Seção de Declarações das variáveis
   nome: caractere


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("qual o seu nome? ")
   leia(nome)
   escreva("olá ", nome, ", é um prazer te conhecer!")


Fimalgoritmo